//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::status::Status;
pub use super::users::{
    Column as UsersColumn, Entity as Users, Model as UsersModel, Relation as UsersRelation,
};
pub use super::video_upload::{
    Column as VideoUploadColumn, Entity as VideoUpload, Model as VideoUploadModel,
    Relation as VideoUploadRelation,
};
pub use super::videos::{
    Column as VideosColumn, Entity as Videos, Model as VideosModel, Relation as VideosRelation,
};
